import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/extras/header";
import { ClerkProvider } from "@clerk/nextjs";
import { shadcn } from "@clerk/themes";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "PrepAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: shadcn,
      }}
    >
      <html lang="en">
        <body className={`${inter.className}`}>
          <Header />
          <main className={"min-h-screen"}> {children} </main>
          {/* Footer */}
          <footer className={"py-8 px-4 border-t"}>
            <div
              className={"max-w-6xl mx-auto flex justify-center items-center"}
            >
              <p className={"text-stone-500 text-sm"}>
                © {new Date().getFullYear()} PrepAI
              </p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
